language: python
python:
  - "2.7"


before_script:
    - wget https://github.com/web2py/web2py/archive/R-2.4.4.zip
    - unzip R-2.4.4.zip
    - export API_BASE_DIR=`pwd`
    - cd web2py-R-2.4.4
    - cd applications
    # move the default welcome app out of the way
    - mv welcome welcome.back
    # make the root of this repo the default application
    - ln -sf $API_BASE_DIR welcome
    - cd ..
    - python web2py.py -i localhost --nogui --debug=0 -p 8000 -a 'supersekret' &> web2py.log &
    - sleep 3 # give the webserver time to startup
    - cat web2py.log
    - cd ..
    - git status -sbu

script:
    - true

after_script:
    - git status -sbu
    - cat web2py-*/web2py.log
    - ps auxw|grep python
    - sudo dmesg | tail -n50
